spring:
  application:
    name: eurekaserver
server:
  port: 8073
eureka:
  instance:
    hostname: eurekaserver3
  client:
    serviceUrl:
      defaultZone: http://eurekaserver2:8072/eureka/, http://eurekaserver:8070/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
   
