spring:
  application:
    name: eureka-server
server:
  port: 8070
eureka:
  instance:
    hostname: eurekaserver
  client:
    serviceUrl:
      defaultZone: http://eurekaserver2:8072/eureka/, http://eurekaserver3:8073/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"