spring:
  application:
    name: eurekaserver
server:
  port: 8072
eureka:
  instance:
    hostname: eurekaserver2
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/, http://eurekaserver3:8073/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
   
